export default {
  login: 'Login',
  tryLogin: 'Try login',
  signUp: 'Create account',
  createAccount: 'Create new account',
  loading: 'Loading',
  password: 'Password',
  passwordConfirmation: 'Password Confirmation',
  email: 'Email',
  username: 'Username',
  firstName: 'First Name',
  lastName: 'Last name',
  home: 'Home',
  homeMessage: 'Welcome',
  profile: 'Profile',
  profileMessage: 'And this one has a nav, but with a different color than the login.',
  logout: 'Logout',
};
